apiVersion: v1
kind: Service
metadata:
  name: lago-service
  namespace: lago-test
spec:
  type: NodePort
  selector:
    app: lago
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: frontend
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: api
  - protocol: TCP
    port: 3001
    targetPort: 3001
    name: pdf